apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: ${NAMESPACE}
spec:
  acme:
    email: ${EMAIL}
    # server: https://acme-v02.api.letsencrypt.org/directory
    # https://acme-staging-v02.api.letsencrypt.org/directory #This is the staging Server from let's encrypt use it when trying things out
    server: ${ACME_SERVER_URL}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        clouddns:
          # The ID of the GCP project
          project: ${PROJECT_ID}
          # This is the secret used to access the service account
          serviceAccountSecretRef:
            name: ${SECRET_NAME}
            key: ${PASSWORD}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ${CERT_NAME}
  namespace: ${NAMESPACE}
spec:
  secretName: ${CERT_NAME}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: '*.${DOMAIN}' 
  dnsNames:
  - '*.${DOMAIN}'
  - ${DOMAIN}
